### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by OutOfBedlam** [machbase/neo-docs#1]
[2023-01-14 10:18:46] ERROR `/apple-touch-icon-precomposed.png' not found.
[2023-01-14 10:18:46] ERROR `/favicon.ico' not found.
[2023-01-14 10:18:46] ERROR `/apple-touch-icon.png' not found.

_Originally posted by @OutOfBedlam in https://github.com/machbase/machbase/issues/2_

**Comment by OutOfBedlam** [comment]
@EdwardLee210 
일전에 요청드린 machbase-neo logo가 준비되면 https://neo.machbase.com/ 에 적용할...

- 일반 favicon
- 위에 에러 발생시키는 apple용 아이콘 부탁합니다.
- android에도 별도의 위와 같은 아이콘이 필요한지 모르겠는데 함께 확인 바랍니다.

**Comment by OutOfBedlam** [comment]
@EdwardLee210 
진행상황 update 바랍니다.

**Comment by EdwardLee210** [comment]
유지수 선임에게 전달했습니다.
apple-touch-icon-precomposed.png 는 Mac Devices에서 사용하는 것이라서 안드로이드는 관련이 없을 것 같습니다.

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
